services:

  order-api:
    build:
      context: ./services/orderapi
    image: order-api:1.0
    container_name: order-api
    ports:
      - "8081:8081"
    networks:
      - order-network

  order-processor:
    build:
      context: ./services/order-processor
    image: order-processor:1.0
    container_name: order-processor
    ports:
      - "8082:8082"
    networks:
      - order-network

  notification-service:
    build:
      context: ./services/notification-service
    image: notification-service:1.0
    container_name: notification-service
    ports:
      - "8083:8083"
    networks:
      - order-network

networks:
  order-network:
    driver: bridge