apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: {{ .Values.notificationService.service.type }}
  selector:
    app: notification-service
  ports:
    - port: {{ .Values.notificationService.service.port }}
      targetPort: {{ .Values.notificationService.service.port }}