apiVersion: v1
kind: Service
metadata:
  name: order-processor
spec:
  type: {{ .Values.orderProcessor.service.type }}
  selector:
    app: order-processor
  ports:
    - port: {{ .Values.orderProcessor.service.port }}
      targetPort: {{ .Values.orderProcessor.service.port }}