apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor
spec:
  replicas: {{ .Values.orderProcessor.replicaCount }}
  selector:
    matchLabels:
      app: order-processor
  template:
    metadata:
      labels:
        app: order-processor
    spec:
      containers:
        - name: order-processor
          image: "{{ .Values.orderProcessor.image.repository }}:{{ .Values.orderProcessor.image.tag }}"
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.orderProcessor.service.port }}